#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint
npm run lint

# Format all project files
npm run format

# Re-stage only the previously staged files that were formatted by prettier
git diff --cached --name-only | while read -r file; do
    if [ -f "$file" ]; then
        git add "$file"
    fi
done

# Build the project
npm run build