#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Define color variables
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m' # No color

# Run pre-commit
echo -e "\n${GREEN}Running pre-commit hook${NC}"

staged_files=$(git diff --name-only --cached --diff-filter=ACM)
files_to_format=$(echo "$staged_files" | grep -E '\.(js|jsx|ts|tsx|vue|json)$')
files_to_lint=$(echo "$staged_files" | grep -E '\.(js|jsx|ts|tsx|vue)$')

# Run prettier to format staged files
echo -e "\n${CYAN}Running prettier on staged files${NC}"
npm run format-staged $files_to_format

# Re-stage formatted files
echo -e "\n${GREEN}Re-staging prettified files${NC}"
git add -v $files_to_format

# Run lint on staged files
echo -e "\n${CYAN}Running lint-staged${NC}"
npm run lint $files_to_lint

# Re-stage linted files
echo -e "\n${GREEN}Re-staging linted files${NC}"
git add -v $files_to_lint

# Build project
echo -e "\n${CYAN} Building project${NC}"
npm run build